"""Audio-to-MIDI transcription via onset detection + pitch estimation.

Converts generated audio waveforms into MIDI note events using:
1. Onset detection (energy-based) to find note boundaries
2. Pitch estimation (autocorrelation) to determine note values
3. MIDI file generation using the standard MIDI format

This is a basic transcription suitable for monophonic or simple
polyphonic content. It works best with melodic lines, basslines,
and simple chord patterns generated by MusicGen.
"""

import struct
from pathlib import Path

import numpy as np


def audio_to_midi(
    audio: np.ndarray,
    sample_rate: int,
    bpm: float = 120.0,
    min_note_duration: float = 0.05,
    onset_threshold: float = 0.15,
    velocity: int = 100,
) -> bytes:
    """Convert audio array to MIDI file bytes.

    Args:
        audio: Mono audio array (1D numpy float32).
        sample_rate: Sample rate of the audio.
        bpm: Tempo for MIDI timing.
        min_note_duration: Minimum note duration in seconds.
        onset_threshold: Energy threshold for onset detection (0-1).
        velocity: MIDI velocity for all notes (1-127).

    Returns:
        MIDI file as bytes (Standard MIDI File format 0).
    """
    if audio.ndim > 1:
        audio = audio.mean(axis=0) if audio.shape[0] <= 2 else audio.flatten()

    # Normalize
    peak = np.max(np.abs(audio))
    if peak > 0:
        audio = audio / peak

    # Detect onsets via energy envelope
    hop = int(sample_rate * 0.01)  # 10ms hop
    frame_size = int(sample_rate * 0.03)  # 30ms frame
    num_frames = (len(audio) - frame_size) // hop

    if num_frames < 2:
        return _empty_midi(bpm)

    energy = np.zeros(num_frames)
    for i in range(num_frames):
        start = i * hop
        frame = audio[start : start + frame_size]
        energy[i] = np.sqrt(np.mean(frame**2))

    # Onset = energy increase above threshold
    energy_diff = np.diff(energy)
    energy_diff = np.maximum(energy_diff, 0)
    max_diff = np.max(energy_diff) if np.max(energy_diff) > 0 else 1.0
    energy_diff /= max_diff

    onsets = []
    min_gap_frames = int(min_note_duration * sample_rate / hop)
    last_onset = -min_gap_frames

    for i in range(len(energy_diff)):
        if energy_diff[i] > onset_threshold and (i - last_onset) >= min_gap_frames:
            onsets.append(i)
            last_onset = i

    if not onsets:
        return _empty_midi(bpm)

    # Estimate pitch at each onset
    notes = []
    for idx, onset_frame in enumerate(onsets):
        start_sample = onset_frame * hop
        # Use a larger window for pitch detection
        pitch_window = int(sample_rate * 0.05)  # 50ms
        end_sample = min(start_sample + pitch_window, len(audio))
        segment = audio[start_sample:end_sample]

        if len(segment) < 256:
            continue

        midi_note = _estimate_pitch(segment, sample_rate)
        if midi_note is None:
            continue

        # Calculate note duration (until next onset or end of audio)
        onset_time = start_sample / sample_rate
        if idx + 1 < len(onsets):
            next_time = onsets[idx + 1] * hop / sample_rate
            duration = next_time - onset_time
        else:
            duration = len(audio) / sample_rate - onset_time

        duration = max(duration, min_note_duration)
        notes.append((onset_time, duration, midi_note, velocity))

    if not notes:
        return _empty_midi(bpm)

    return _build_midi(notes, bpm)


def _estimate_pitch(segment: np.ndarray, sample_rate: int) -> int | None:
    """Estimate MIDI note number using autocorrelation."""
    # Autocorrelation
    n = len(segment)
    corr = np.correlate(segment, segment, mode="full")
    corr = corr[n:]  # Only positive lags

    # Find first peak after the initial decline
    # Skip very short lags (high frequencies above MIDI range)
    min_lag = int(sample_rate / 4000)  # ~C8
    max_lag = int(sample_rate / 30)  # ~B0

    if max_lag >= len(corr):
        max_lag = len(corr) - 1
    if min_lag >= max_lag:
        return None

    search = corr[min_lag:max_lag]
    if len(search) < 3:
        return None

    # Find the highest peak
    peak_idx = np.argmax(search) + min_lag
    if corr[peak_idx] < 0.1 * corr[0]:
        return None  # Too weak — probably noise

    freq = sample_rate / peak_idx

    # Convert frequency to MIDI note
    if freq < 20 or freq > 4000:
        return None

    midi_note = int(round(69 + 12 * np.log2(freq / 440.0)))
    return max(0, min(127, midi_note))


def _empty_midi(bpm: float) -> bytes:
    """Return a valid but empty MIDI file."""
    return _build_midi([], bpm)


def _build_midi(notes: list[tuple[float, float, int, int]], bpm: float) -> bytes:
    """Build a Standard MIDI File (format 0) from note events.

    Args:
        notes: List of (time_seconds, duration_seconds, midi_note, velocity).
        bpm: Tempo in beats per minute.
    """
    ticks_per_beat = 480
    us_per_beat = int(60_000_000 / bpm)

    # Build track events
    events: list[tuple[int, bytes]] = []

    # Tempo meta event
    events.append((0, b"\xff\x51\x03" + us_per_beat.to_bytes(3, "big")))

    # Note events
    for time_s, dur_s, note, vel in notes:
        tick_on = int(time_s * bpm / 60 * ticks_per_beat)
        tick_off = int((time_s + dur_s) * bpm / 60 * ticks_per_beat)
        events.append((tick_on, bytes([0x90, note, vel])))  # Note on
        events.append((tick_off, bytes([0x80, note, 0])))  # Note off

    # End of track
    if events:
        last_tick = max(t for t, _ in events)
    else:
        last_tick = 0
    events.append((last_tick, b"\xff\x2f\x00"))

    # Sort by tick, stable
    events.sort(key=lambda x: x[0])

    # Encode with delta times
    track_data = bytearray()
    prev_tick = 0
    for tick, data in events:
        delta = tick - prev_tick
        track_data.extend(_encode_var_length(delta))
        track_data.extend(data)
        prev_tick = tick

    # Build file
    header = b"MThd" + struct.pack(">IHHh", 6, 0, 1, ticks_per_beat)
    track = b"MTrk" + struct.pack(">I", len(track_data)) + bytes(track_data)

    return header + track


def _encode_var_length(value: int) -> bytes:
    """Encode an integer as MIDI variable-length quantity."""
    if value < 0:
        value = 0
    result = bytearray()
    result.append(value & 0x7F)
    value >>= 7
    while value > 0:
        result.append((value & 0x7F) | 0x80)
        value >>= 7
    result.reverse()
    return bytes(result)


def save_midi(midi_bytes: bytes, path: str | Path) -> None:
    """Write MIDI bytes to a file."""
    Path(path).write_bytes(midi_bytes)
